/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/9F2hNiaiCef
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'
import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { CardContent, Card } from "@/components/ui/card"

export function Chat() {
  return (
    <Card className="w-full max-w-lg">
      <CardContent className="flex flex-col space-y-4">
        <div className="flex items-center space-x-4">
          <img
            alt="Superfood Icon"
            className="rounded-full"
            height="40"
            src="/placeholder.svg"
            style={{
              aspectRatio: "40/40",
              objectFit: "cover",
            }}
            width="40"
          />
          <div className="flex-1">
            <h3 className="text-lg font-bold">supaFood Foodie342</h3>
            <p className="text-sm text-gray-500 dark:text-gray-400">Online</p>
          </div>
        </div>
        <div className="flex flex-col space-y-2">
          <div>
            Hi there! Did you know that you can add a tablespoon of chia seeds to your smoothie for an extra nutritional
            boost?
          </div>
          <div>
            Chia seeds are an excellent source of omega-3 fatty acids, antioxidants, fiber, iron, and calcium. They have
            been associated with several health benefits, including improved digestion, better heart health, and
            increased energy levels.
          </div>
          <div className="grid grid-cols-2 gap-2">
            <div>
              <p className="text-sm font-semibold">Omega-3 Fatty Acids</p>
              <p className="text-xs text-gray-500 dark:text-gray-400">10% (1g)</p>
            </div>
            <div>
              <p className="text-sm font-semibold">Antioxidants</p>
              <p className="text-xs text-gray-500 dark:text-gray-400">15% (2g)</p>
            </div>
            <div>
              <p className="text-sm font-semibold">Fiber</p>
              <p className="text-xs text-gray-500 dark:text-gray-400">20% (3g)</p>
            </div>
            <div>
              <p className="text-sm font-semibold">Iron</p>
              <p className="text-xs text-gray-500 dark:text-gray-400">5% (0.5g)</p>
            </div>
            <div>
              <p className="text-sm font-semibold">Calcium</p>
              <p className="text-xs text-gray-500 dark:text-gray-400">8% (1g)</p>
            </div>
          </div>
        </div>
        <div className="flex items-center space-x-2">
          <Button size="sm">Recipes!</Button>
          <Button size="sm">Background!</Button>
          <Button size="sm">Nutrition!</Button>
        </div>
      </CardContent>
    </Card>
  )
}
