/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/cUmNyLFWEnG
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'
import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { DropdownMenuTrigger, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"
import { Card } from "@/components/ui/card"

export function Dashboard() {
  return (
    <div className="flex flex-col w-full min-h-screen">
      <header className="flex items-center h-16 px-4 border-b shrink-0 md:px-6">
        <nav className="flex-col hidden gap-6 text-lg font-medium md:flex md:flex-row md:items-center md:gap-5 md:text-sm lg:gap-6">
          <Link className="flex items-center gap-2 text-lg font-semibold md:text-base" href="#">
            <Package2Icon className="w-6 h-6" />
            <span className="sr-only">Acme Inc</span>
          </Link>
          <Link className="text-gray-500 dark:text-gray-400" href="#">
            Recipes
          </Link>
          <Link className="text-gray-500 dark:text-gray-400" href="#">
            Categories
          </Link>
          <Link className="font-bold" href="#">
            Feedback
          </Link>
        </nav>
        <div className="flex items-center w-full gap-4 md:ml-auto md:gap-2 lg:gap-4">
          <form className="flex-1 ml-auto sm:flex-initial">
            <div className="relative">
              <SearchIcon className="absolute left-2.5 top-2.5 h-4 w-4 text-gray-500 dark:text-gray-400" />
              <Input
                className="pl-8 sm:w-[300px] md:w-[200px] lg:w-[300px]"
                placeholder="Search feedback..."
                type="search"
              />
            </div>
          </form>
          <Button size="sm" variant="outline">
            New Recipe
          </Button>
          <Button size="sm" variant="outline">
            Export
          </Button>
          <Button size="sm" variant="outline">
            Import
          </Button>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button
                className="rounded-full border border-gray-200 border-transparent dark:border-gray-800 dark:border-gray-850 dark:border-gray-800"
                size="icon"
                variant="ghost"
              >
                <img
                  alt="Avatar"
                  className="rounded-full"
                  height="32"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "32/32",
                    objectFit: "cover",
                  }}
                  width="32"
                />
                <span className="sr-only">Toggle user menu</span>
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuLabel>My Account</DropdownMenuLabel>
              <DropdownMenuSeparator />
              <DropdownMenuItem>Settings</DropdownMenuItem>
              <DropdownMenuItem>Support</DropdownMenuItem>
              <DropdownMenuSeparator />
              <DropdownMenuItem>Logout</DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </header>
      <main className="flex min-h-[calc(100vh-_theme(spacing.16))] flex-1 flex-col gap-4 p-4 md:gap-8 md:p-10">
        <Card>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead className="w-[100px]">Recipe</TableHead>
                <TableHead className="min-w-[150px]">User</TableHead>
                <TableHead className="hidden md:table-cell">Date</TableHead>
                <TableHead>Feedback</TableHead>
                <TableHead>Rating</TableHead>
                <TableHead>SuperFood Highlight</TableHead>
                <TableHead className="text-right">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableRow>
                <TableCell className="font-medium">Lasagna</TableCell>
                <TableCell>olivia.martin@example.com</TableCell>
                <TableCell className="hidden md:table-cell">February 20, 2022</TableCell>
                <TableCell>
                  This lasagna was delicious! I loved the blend of cheeses and the rich tomato sauce. It was a bit
                  heavy, but overall, a fantastic dish.
                </TableCell>
                <TableCell>4.5</TableCell>
                <TableCell>Spinach</TableCell>
                <TableCell className="text-right">
                  <Button size="icon" variant="ghost">
                    <MoreHorizontalIcon className="w-4 h-4" />
                    <span className="sr-only">Actions</span>
                  </Button>
                </TableCell>
              </TableRow>
              <TableRow>
                <TableCell className="font-medium">Chocolate Cake</TableCell>
                <TableCell>ava.johnson@example.com</TableCell>
                <TableCell className="hidden md:table-cell">January 5, 2022</TableCell>
                <TableCell>
                  The chocolate cake was a bit dry, and the frosting was too sweet for my taste. I would have preferred
                  a more moist cake with a darker, less sugary frosting.
                </TableCell>
                <TableCell>3.2</TableCell>
                <TableCell>Blueberries</TableCell>
                <TableCell className="text-right">
                  <Button size="icon" variant="ghost">
                    <MoreHorizontalIcon className="w-4 h-4" />
                    <span className="sr-only">Actions</span>
                  </Button>
                </TableCell>
              </TableRow>
              <TableRow>
                <TableCell className="font-medium">Spaghetti Carbonara</TableCell>
                <TableCell>michael.johnson@example.com</TableCell>
                <TableCell className="hidden md:table-cell">August 3, 2021</TableCell>
                <TableCell>
                  The spaghetti carbonara was excellent. It had the perfect balance of creaminess and saltiness. I would
                  definitely order this again.
                </TableCell>
                <TableCell>4.8</TableCell>
                <TableCell>Kale</TableCell>
                <TableCell className="text-right">
                  <Button size="icon" variant="ghost">
                    <MoreHorizontalIcon className="w-4 h-4" />
                    <span className="sr-only">Actions</span>
                  </Button>
                </TableCell>
              </TableRow>
              <TableRow>
                <TableCell className="font-medium">Chicken Tikka Masala</TableCell>
                <TableCell>lisa.anderson@example.com</TableCell>
                <TableCell className="hidden md:table-cell">July 15, 2021</TableCell>
                <TableCell>
                  The chicken tikka masala was flavorful and aromatic. The chicken was tender, and the sauce was rich
                  and creamy without being too heavy. It was a delightful dish, and I would recommend it to others.
                </TableCell>
                <TableCell>4.6</TableCell>
                <TableCell>Quinoa</TableCell>
                <TableCell className="text-right">
                  <Button size="icon" variant="ghost">
                    <MoreHorizontalIcon className="w-4 h-4" />
                    <span className="sr-only">Actions</span>
                  </Button>
                </TableCell>
              </TableRow>
              <TableRow>
                <TableCell className="font-medium">Cheeseburger</TableCell>
                <TableCell>samantha.green@example.com</TableCell>
                <TableCell className="hidden md:table-cell">June 5, 2021</TableCell>
                <TableCell>
                  The cheeseburger was a bit disappointing. The patty was overcooked and dry, and the burger was lacking
                  in flavor. The fries were good, though.
                </TableCell>
                <TableCell>2.5</TableCell>
                <TableCell>Avocado</TableCell>
                <TableCell className="text-right">
                  <Button size="icon" variant="ghost">
                    <MoreHorizontalIcon className="w-4 h-4" />
                    <span className="sr-only">Actions</span>
                  </Button>
                </TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </Card>
      </main>
    </div>
  )
}

function MoreHorizontalIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="1" />
      <circle cx="19" cy="12" r="1" />
      <circle cx="5" cy="12" r="1" />
    </svg>
  )
}


function Package2Icon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 9h18v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9Z" />
      <path d="m3 9 2.45-4.9A2 2 0 0 1 7.24 3h9.52a2 2 0 0 1 1.8 1.1L21 9" />
      <path d="M12 3v6" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}
